// SPDX-License-Identifier: LGPL-3.0-or-later

package seccure

import (
	"encoding/asn1"
	"encoding/hex"
	"encoding/json"
	"math/big"
	"os"
	"path/filepath"
	"testing"
)

// Wycheproof is Google's adversarial cryptographic test corpus. Each entry
// is a carefully crafted (signature, message, pubkey, expected_result)
// tuple — many of them designed to trip up real-world ECDSA implementations
// (out-of-range r/s, malformed encodings, near-boundary scalars, modified
// hashes, etc.).
//
// The ASN.1/DER-encoded (r, s) wire format Wycheproof uses isn't what
// SECCURE uses (we pack sig_int = s*n + r big-endian). The test extracts
// (r, s) from the DER blob and repacks into SECCURE's format before
// calling Verify, exercising our verification math against the same edge
// cases.
//
// # Curve coverage
//
// Only secp521r1 vectors are imported. The reason is a deliberate scheme
// difference: standard NIST ECDSA truncates the message hash to bitlen(n)
// bits before reducing mod n, while SECCURE uses the full hash mod n
// (reference/py/__init__.py:686 and reference/c/protocol.c:197-199). For
// any curve whose order is shorter than the hash output, these rules
// produce different e values and Wycheproof's standard-rule signatures
// would not validate under SECCURE's non-standard verify path. For
// secp521r1 with SHA-512 the orders coincide (521-bit order ≥ 512-bit
// hash, no truncation in either spec) and the corpus applies cleanly.
//
// Adversarial coverage for the smaller curves comes from the cross-impl
// vector suite (testdata/vectors.json) instead — those signatures are
// generated by py-seccure under the same scheme, so any divergence shows
// up there.

type wycheproofFile struct {
	TestGroups []struct {
		PublicKey struct {
			Curve string `json:"curve"`
			Wx    string `json:"wx"`
			Wy    string `json:"wy"`
		} `json:"publicKey"`
		Tests []struct {
			TcID    int      `json:"tcId"`
			Comment string   `json:"comment"`
			Flags   []string `json:"flags"`
			Msg     string   `json:"msg"`
			Sig     string   `json:"sig"`
			Result  string   `json:"result"`
		} `json:"tests"`
	} `json:"testGroups"`
}

// parseStrictECDSADER parses Wycheproof's standard ECDSA-over-DER format:
//
//   SEQUENCE { r INTEGER, s INTEGER }
//
// strictly, rejecting:
//   - non-SEQUENCE outer tag
//   - any trailing bytes after the SEQUENCE
//   - any trailing bytes after `s` inside the SEQUENCE (e.g. appended
//     null, repeated element, padding zeros)
//
// Returns (nil, false) on any structural anomaly. Used only inside the
// Wycheproof test harness — go-seccure's production code never parses
// DER (SECCURE packs signatures as a single big-endian integer instead).
func parseStrictECDSADER(der []byte) (r, s *big.Int, ok bool) {
	var outer asn1.RawValue
	rest, err := asn1.Unmarshal(der, &outer)
	if err != nil || len(rest) != 0 {
		return nil, nil, false
	}
	if outer.Class != asn1.ClassUniversal || outer.Tag != asn1.TagSequence || !outer.IsCompound {
		return nil, nil, false
	}

	body := outer.Bytes
	rest, err = asn1.Unmarshal(body, &r)
	if err != nil {
		return nil, nil, false
	}
	rest, err = asn1.Unmarshal(rest, &s)
	if err != nil || len(rest) != 0 {
		return nil, nil, false
	}
	return r, s, true
}

// Only curves where SECCURE's "hash mod n" rule produces the same e as
// NIST ECDSA's "leftmost bitlen(n) bits" rule. See the package comment
// above for why p256/p384 are intentionally excluded.
var wycheproofCurves = map[string]Curve{
	"secp521r1": CurveP521,
}

func TestWycheproofECDSAVerify(t *testing.T) {
	files, err := filepath.Glob("testdata/wycheproof/ecdsa_*_sha512_test.json")
	if err != nil {
		t.Fatalf("glob: %v", err)
	}
	if len(files) == 0 {
		t.Skip("no wycheproof vectors in testdata/wycheproof/")
	}

	for _, path := range files {
		t.Run(filepath.Base(path), func(t *testing.T) {
			data, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("read: %v", err)
			}
			var f wycheproofFile
			if err := json.Unmarshal(data, &f); err != nil {
				t.Fatalf("parse: %v", err)
			}

			var ran, passed, mismatches int
			for _, group := range f.TestGroups {
				curve, ok := wycheproofCurves[group.PublicKey.Curve]
				if !ok {
					continue
				}
				cp := lookupCurve(curve)
				if cp == nil {
					continue
				}

				// Reconstruct the SECCURE-format compact pubkey from
				// Wycheproof's wx/wy coordinates.
				wx, ok := new(big.Int).SetString(group.PublicKey.Wx, 16)
				if !ok {
					t.Fatalf("bad wx hex: %s", group.PublicKey.Wx)
				}
				wy, ok := new(big.Int).SetString(group.PublicKey.Wy, 16)
				if !ok {
					t.Fatalf("bad wy hex: %s", group.PublicKey.Wy)
				}
				pubBin, err := compress(&point{x: wx, y: wy}, cp)
				if err != nil {
					t.Fatalf("compress wycheproof pubkey: %v", err)
				}
				pubkey, err := encodeCompact(pubBin, cp.pkLenCompact)
				if err != nil {
					t.Fatalf("encodeCompact wycheproof pubkey: %v", err)
				}

				for _, tc := range group.Tests {
					ran++
					msg, err := hex.DecodeString(tc.Msg)
					if err != nil {
						t.Errorf("tcId %d: bad msg hex: %v", tc.TcID, err)
						continue
					}
					sigDER, err := hex.DecodeString(tc.Sig)
					if err != nil {
						t.Errorf("tcId %d: bad sig hex: %v", tc.TcID, err)
						continue
					}

					// Attempt to repack DER (r, s) into SECCURE format.
					// Parse failure or out-of-range (r, s) is a legitimate
					// rejection — for "invalid" tests we expect this.
					verifyErr := repackAndVerify(sigDER, msg, pubkey, curve, cp)

					ok := classifyMatch(tc.Result, verifyErr)
					if ok {
						passed++
					} else {
						mismatches++
						// Report up to 10 mismatches to keep output readable.
						if mismatches <= 10 {
							t.Errorf("tcId %d (%s): result=%s, got verifyErr=%v\n  flags: %v\n  comment: %s",
								tc.TcID, group.PublicKey.Curve, tc.Result, verifyErr,
								tc.Flags, tc.Comment)
						}
					}
				}
			}
			t.Logf("%s: ran=%d passed=%d mismatches=%d", filepath.Base(path), ran, passed, mismatches)
		})
	}
}

// repackAndVerify parses Wycheproof's DER signature strictly, repacks
// (r, s) into SECCURE's sig_int = s*n + r format, and runs Verify.
// Returns nil if the signature verifies, an error otherwise.
func repackAndVerify(sigDER, msg []byte, pubkey string, curve Curve, cp *curveParams) error {
	r, s, ok := parseStrictECDSADER(sigDER)
	if !ok {
		return ErrInvalidSignature
	}
	// SECCURE requires both r, s strictly in [1, n-1]. Wycheproof has
	// out-of-range cases by design.
	one := big.NewInt(1)
	if r.Cmp(one) < 0 || r.Cmp(cp.n) >= 0 || s.Cmp(one) < 0 || s.Cmp(cp.n) >= 0 {
		return ErrInvalidSignature
	}
	// Pack: sig_int = s*n + r, big-endian, exactly 2*orderLenBin bytes.
	sigInt := new(big.Int).Mul(s, cp.n)
	sigInt.Add(sigInt, r)
	binSig := make([]byte, cp.sigLenBin)
	sib := sigInt.Bytes()
	if len(sib) > cp.sigLenBin {
		return ErrInvalidSignature
	}
	copy(binSig[cp.sigLenBin-len(sib):], sib)

	return VerifyBinary(msg, binSig, pubkey, curve)
}

// classifyMatch decides whether our Verify result matches Wycheproof's
// expectation. Wycheproof labels:
//
//   "valid"      — the signature must verify
//   "invalid"    — must NOT verify
//   "acceptable" — either is OK; flag covers historical permissive
//                  parsers; we treat it as a pass.
func classifyMatch(expected string, verifyErr error) bool {
	switch expected {
	case "valid":
		return verifyErr == nil
	case "invalid":
		return verifyErr != nil
	case "acceptable":
		return true
	default:
		return false
	}
}
